# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  fec-workflow:
    jobs:
      - fec-test:
        context: FEC-context

jobs:
  fec-test:
    docker:
    - node/test:
        version: '15.1'
    steps:
      - run: echo FEC_GIT
        # This is the node version to use for the `cimg/node` tag
        # https://circleci.com/developer/images/image/cimg/node
        # Relevant tags can be found on the CircleCI Developer Hub