# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  write-config:
    steps:
      run: echo 'export var auth = { TOKEN: \'$TOKEN \' };' >> config.js


workflows:
  FEC-test:
    jobs:
      - write-config
      - node/test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
