# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# orbs:
#   node: circleci/node@4.1

workflows:
  fec:
    jobs:
      - run-tests:
          context: FEC-context

jobs:
  run-tests:
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run:
          name: "echo environment variable from FEC context"
          command: echo export FEC_GIT="FEC_GIT" >> $BASH_ENV/.circlerc
      - run: npm install
      - run: npm test

# workflows:
#   fec-test:
#     jobs:
#       - node/test:
#           version: '15.1'
#         # This is the node version to use for the `cimg/node` tag
#         # https://circleci.com/developer/images/image/cimg/node
#         # Relevant tags can be found on the CircleCI Developer Hub


