# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  fec:
    jobs:
      - run-tests:
          context: FEC-context

jobs:
  run-tests:
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: "echo environment variable from FEC context and run npm test"
          command: |
            echo export var auth={TOKEN:\'${FEC_GIT}\'} >> config.js
            npm test


